#!/usr/bin/env bash

# Automate the process of making API requests to the Pokémon API and saving the results to a file
# It should save the response to a json file: data.json
# If the request fails, it should log the error to an error file: errors.txt

URL="https://pokeapi.co/api/v2/pokemon/"
curl -X GET "$URL" 1>data.json 2>errors.txt