#!/usr/bin/env bash

# A script that makes a request to the Pokémon API (https://pokeapi.co/api/v2/pokemon/ ) and retrieves data for a specific Pokémon Pikachu
# It should save the response to a json file: data.json
# If the request fails, it should log the error to an error file: errors.txt

URL="https://pokeapi.co/api/v2/pokemon/pikachu"
curl -X GET "$URL" 1>data.json 2>errors.txt