#!/usr/bin/env bash

# A  script that loops through a list of Pokémon [Bulbasaur, Ivysaur, Venusaur, Charmander, Charmeleon.]

# For each Pokémon, retrieve its data from the API and save it to a separate file named after the Pokémon (e.g., pikachu.json, bulbasaur.json…).

# Handle any potential rate-limiting issues by adding a delay between requests.

BASE_URL="https://pokeapi.co/api/v2/pokemon"
pokemons=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")

for pokemon in "${pokemons[@]}";
do
    echo "fetching data for $pokemon..."
    curl -sL "$BASE_URL/$pokemon" -o "$pokemon.json"
    sleep 4
done