#!/usr/bin/env bash

# A script that extracts the Pokémon’s name, height, weight, and type from the JSON file created in Task 0.

# Format the output in a human-readable way,“Pikachu is of type Electric, weighs 6kg, and is 0.4m tall.”

# You should only use these commands: jq, awk, sed

JSON_INPUT=data.json

name=$(jq -r '(.name | (.[0:1] | ascii_upcase) + .[1:])' "$JSON_INPUT");
type=$(jq -r '(.types[0].type.name)' "$JSON_INPUT");
formatted_weight=$(jq -r '(.weight/10)' "$JSON_INPUT");
formatted_height=$(jq -r '(.height/10)' "$JSON_INPUT");

echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."


# string interpolation using jq can acheive same result as shown below

# jq -r '. | "\(.name | (.[0:1] | ascii_upcase) + .[1:]) is of type \(.types[0].type.name), weighs \(.weight/10)kg, and is \(.height/10)m tall."' data.json
